name: ProtosPing

on:
  push:
    branches:
      - dev

jobs:
  new-protos-ping:
    runs-on: ubuntu-latest
    name: Ping on new protos to review
    steps:
      - name: Post to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "New protos available for review: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
